### ISSUE TITLE
Configgin breaks with PENDING status POD

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/configgin#77]
Hello,

The following scenario broke my kube cluster during an upgrade.

Taking the example of a single component(e.g. diego-access) which is a kube deployment with 2 replicas, and have default values for `maxSurge`(1) and `maxUnavailable`(1).

During the `upgrade` kube will bring a new POD(due to the maxSurge)  and take one down(maxUnavailable). However, due to the POD affinity and NodeSelector configurations, the new POD will not find nodes available to schedule himself, so it stays under a `PENDING` status, which will cause configgin to break.

Configgin code will try to get the following from the POD `kubectl -n cf get SOMEPOD -o json | jq .status.containerStatuses`(see [get_pods_per_image](https://github.com/SUSE/configgin/blob/master/lib/kube_link_generator.rb#L87) ), but because is empty, it will break, making the POD that was supposed to be remove(due to maxUnavailable)  to get a `CrashLoopBackOff` status.

I have a [fork branch](https://github.com/qu1queee/configgin/blob/pending_pods_issue/lib/kube_link_generator.rb#L87) that will check first if the pod data`.status.containerStatuses` is empty, before trying to access it.

Can someone take a look on this, opinions?

Regards,
Enrique Encalada

**Comment by mook-as** [comment]
(Style nit: `if !` → `unless`)

This would mean that we'd have things thinking they were bootstrap (because `pods_per_image[self…]` is `nil`, `get_pods_per_image` returns `0` for that pod), right?  Ah, no, because it's `pending`, that code can't run. So things only think they are bootstrap if they _are_ the only pod with that image.

So that looks fine, then. Would you be interested in creating a PR for that?

**Comment by qu1queee** [comment]
Hello,

Thanks for your reply. Yes, PR is #78 .
I move to use `unless` and added a test case that expects `be_falsey` due to the `nil` `containerStatuses` key in the pod metadata.

I will require a new `configgin` version, similar to what was done in #76 . Probably a configgin `0.15.2` gem. I can PR that, once this PR is merged.

Thanks in advance.

Regards,
Enrique Encalada

**Comment by viovanov** [comment]
#78 is closed
